version: '3'
services:
  api:
        restart: on-failure
        build:
            dockerfile: Dockerfile.dev
            context: './'
        environment:
          USERNAME: 'root'
          PASSWORD: 'password'
          HOST: 'db'
          SCHEMA: 'todos_db'
        ports:
          - '8080:8080'
        expose:
          - '8080'
        depends_on:
            - db
        volumes:
            - ./:/app
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'todos_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: 'localhost'
    ports:
      - '3306:3306'
    expose:
      - '3306'